services:
    app:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        platform: linux/amd64
        volumes:
            - ./frontend:/app:delegated
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            - NEXT_PUBLIC_WEBSOCKET_URL=ws://localhost:8000/ws
            - NODE_ENV=development
            - WATCHPACK_POLLING=true
        command: yarn dev
        depends_on:
            - backend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        platform: linux/amd64
        volumes:
            - ./backend:/app
        ports:
            - "8000:8000"
        environment:
            - PYTHONUNBUFFERED=1
        # command: python3 -u -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-level 'warning'
        tty: false
