FROM  python:3.11.9-alpine

WORKDIR /app

COPY requirements.txt .

RUN apk update \
    && apk add --no-cache graphviz ttf-freefont \
    && pip install --no-cache-dir -r requirements.txt

COPY . .